### ISSUE TITLE
Double point at endpoint (path) for the GraphQL API on the site provoking an error

### ISSUE THREAD

**Issue by webmasterlocafe** [scottyzen/woonuxt#64] opened 2023-09-20 22:15 UTC
Hi team, 

I'm geting an erro on Netlify when deploying : **_Failed to load schema from https://trade.chasleao.com.br/graphql:_**

Aparently the double dot after the URL is cousing it since it woks ok without the double points (https://trade.chasleao.com.br/graphql)

Any sugestion on how to adjust?

<img width="1389" alt="Screenshot 2023-09-20 at 19 08 27" src="https://github.com/scottyzen/woonuxt/assets/145374277/1789cf0e-b347-45ca-a5bc-a92efa199ea7">

**Comment by haiphamhoang** [comment] 2023-09-22 10:44
The error seems to be caused by your Cloudflare firewall. Maybe you should whitelist Netlify IP so it can connect to the GraphQL API.

**Comment by M-GRV** [comment] 2023-10-30 15:09
> Hi team,
> 
> I'm geting an erro on Netlify when deploying : **_Failed to load schema from https://trade.chasleao.com.br/graphql:_**
> 
> Aparently the double dot after the URL is cousing it since it woks ok without the double points (https://trade.chasleao.com.br/graphql)
> 
> Any sugestion on how to adjust?
> 
> <img alt="Screenshot 2023-09-20 at 19 08 27" width="1389" src="https://user-images.githubusercontent.com/145374277/269431859-1789cf0e-b347-45ca-a5bc-a92efa199ea7.png">

From my understanding adding : to the end of the url is not the correct way to hook up the frontend. That's why it works without it. If you are all set, you should close this issue out. 

Thanks!

**Closed** 2023-10-30 16:38 UTC
